-- ============================================================
-- Hệ thống Quản lý Học Viên - Database Schema
-- Cập nhật: 2026-03 (thêm indexes, constraints, triggers)
-- ============================================================

-- Create Classes Table
create table classes (
  id text primary key,
  name text not null,
  category text not null,
  schedule jsonb, -- Stores { morning: [], afternoon: [], evening: [] }
  fee_per_session integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone
);

-- Create Students Table
create table students (
  id text primary key,
  name text not null,
  birth_year integer,
  phone text,
  enroll_date date not null,
  leave_date date,
  class_id text references classes(id),
  status text not null, -- 'Mới nhập học', 'Đang học', 'Đã nghỉ'
  status_history jsonb default '[]'::jsonb,
  discount_rate numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone,
  -- Constraints
  constraint check_student_status check (status in ('Mới nhập học', 'Đang học', 'Đã nghỉ')),
  constraint check_student_dates check (leave_date is null or leave_date >= enroll_date),
  constraint check_student_discount_rate check (discount_rate >= 0 and discount_rate <= 100)
);

-- Create Fees Table (Học phí)
create table fees (
  id text primary key,
  student_id text references students(id),
  amount integer not null,
  date date not null,
  method text, -- 'Tiền mặt', 'Chuyển khoản'
  note text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone,
  -- Constraints
  constraint check_fee_amount check (amount > 0),
  constraint check_fee_method check (method is null or method in ('Tiền mặt', 'Chuyển khoản'))
);

-- Create Extra Attendance Table (Buổi học bổ sung)
create table extra_attendance (
  id text primary key,
  student_id text references students(id),
  date date not null,
  status boolean default true, -- Legacy field, kept for backward compatibility
  fee integer,
  notes text,
  is_recurring boolean default false,
  recurring_pattern jsonb, -- { frequency, startDate, endDate, daysOfWeek/dayOfMonth }
  created_by text,
  updated_by text,
  updated_at timestamp with time zone,
  change_history jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create Holidays Table (Lịch nghỉ)
create table if not exists holidays (
  id text primary key,
  date date not null,
  end_date date,
  description text,
  type text default 'Nghỉ Lễ', -- 'Nghỉ Lễ' or 'Nghỉ đột xuất'
  class_id text references classes(id),
  student_id text references students(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  -- Constraints
  constraint check_holiday_type check (type in ('Nghỉ Lễ', 'Nghỉ đột xuất')),
  constraint check_holiday_dates check (end_date is null or end_date >= date)
);

-- Create Promotions Table (Khuyến mãi cấp lớp)
create table if not exists promotions (
  id bigint generated by default as identity primary key,
  class_id text references classes(id) on delete cascade,
  month text not null, -- Format: YYYY-MM
  discount_rate numeric default 0,
  discount_amount numeric default 0,
  discount_type text default 'percent', -- 'percent' | 'amount'
  excluded_student_ids jsonb default '[]'::jsonb,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  -- Constraints
  constraint check_promotions_discount_type check (discount_type in ('percent', 'amount')),
  constraint check_promotions_discount_rate check (discount_rate >= 0 and discount_rate <= 100),
  constraint check_promotions_discount_amount check (discount_amount >= 0),
  constraint uq_promotions_class_month unique (class_id, month)
);

-- Create Student Promotions Table (Khuyến mãi cấp học sinh theo tháng)
create table if not exists student_promotions (
  id bigint generated by default as identity primary key,
  student_id text references students(id) on delete cascade,
  month text not null, -- Format: YYYY-MM
  discount_rate numeric default 0,
  discount_amount numeric default 0,
  discount_type text default 'percent', -- 'percent' | 'amount'
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  -- Constraints
  constraint check_student_promotions_discount_type check (discount_type in ('percent', 'amount')),
  constraint check_student_promotions_discount_rate check (discount_rate >= 0 and discount_rate <= 100),
  constraint check_student_promotions_discount_amount check (discount_amount >= 0),
  constraint uq_student_promotions_student_month unique (student_id, month)
);

-- Create Messages Table (Thông báo)
create table if not exists messages (
  id bigint generated by default as identity primary key,
  author text default 'Admin',
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create Backups Table (Sao lưu dữ liệu)
create table if not exists backups (
  id bigint generated by default as identity primary key,
  data jsonb not null,
  filename text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- ============================================================
-- INDEXES (Performance Optimization)
-- ============================================================

-- students
create index if not exists idx_students_class_id on students(class_id);
create index if not exists idx_students_status on students(status);

-- fees
create index if not exists idx_fees_student_id on fees(student_id);
create index if not exists idx_fees_date on fees(date);
create index if not exists idx_fees_student_date on fees(student_id, date);

-- extra_attendance
create index if not exists idx_extra_attendance_student_id on extra_attendance(student_id);
create index if not exists idx_extra_attendance_date on extra_attendance(date);
create index if not exists idx_extra_attendance_student_date on extra_attendance(student_id, date);

-- holidays
create index if not exists idx_holidays_class_id on holidays(class_id);
create index if not exists idx_holidays_student_id on holidays(student_id);
create index if not exists idx_holidays_date on holidays(date);

-- promotions
create index if not exists idx_promotions_class_id on promotions(class_id);
create index if not exists idx_promotions_class_month on promotions(class_id, month);

-- student_promotions
create index if not exists idx_student_promotions_student_id on student_promotions(student_id);
create index if not exists idx_student_promotions_student_month on student_promotions(student_id, month);

-- ============================================================
-- TRIGGERS (Auto-update updated_at)
-- ============================================================

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create or replace trigger trg_classes_updated_at
  before update on classes
  for each row execute function set_updated_at();

create or replace trigger trg_students_updated_at
  before update on students
  for each row execute function set_updated_at();

create or replace trigger trg_fees_updated_at
  before update on fees
  for each row execute function set_updated_at();

create or replace trigger trg_extra_attendance_updated_at
  before update on extra_attendance
  for each row execute function set_updated_at();

-- ============================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================

alter table public.classes enable row level security;
alter table public.students enable row level security;
alter table public.fees enable row level security;
alter table public.extra_attendance enable row level security;
alter table public.holidays enable row level security;
alter table public.promotions enable row level security;
alter table public.messages enable row level security;
alter table public.backups enable row level security;
alter table public.student_promotions enable row level security;

-- Helper function: read app secret from request headers
create or replace function get_app_secret() returns text as $$
  select current_setting('request.headers', true)::json->>'x-app-secret';
$$ language sql stable set search_path = public;

-- ============================================================
-- POLICIES
-- Public Read, Restricted Write (requires x-app-secret header)
-- ============================================================

-- Classes
create policy "Public Read Access" on public.classes for select to anon using (true);
create policy "Restricted Write Access" on public.classes for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');

-- Students
create policy "Public Read Access" on public.students for select to anon using (true);
create policy "Restricted Write Access" on public.students for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');

-- Fees
create policy "Public Read Access" on public.fees for select to anon using (true);
create policy "Restricted Write Access" on public.fees for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');

-- Extra Attendance
create policy "Public Read Access" on public.extra_attendance for select to anon using (true);
create policy "Restricted Write Access" on public.extra_attendance for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');

-- Holidays
create policy "Public Read Access" on public.holidays for select to anon using (true);
create policy "Restricted Write Access" on public.holidays for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');

-- Promotions
create policy "Public Read Access" on public.promotions for select to anon using (true);
create policy "Restricted Write Access" on public.promotions for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');

-- Messages
create policy "Public Read Access" on public.messages for select to anon using (true);
create policy "Restricted Write Access" on public.messages for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');

-- Backups
create policy "Public Read Access" on public.backups for select to anon using (true);
create policy "Restricted Write Access" on public.backups for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');

-- Student Promotions
create policy "Public Read Access" on public.student_promotions for select to anon using (true);
create policy "Restricted Write Access" on public.student_promotions for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');
