-- Create Classes Table
create table classes (
  id text primary key,
  name text not null,
  category text not null,
  schedule jsonb, -- Stores { morning: [], afternoon: [], evening: [] }
  fee_per_session integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create Students Table
create table students (
  id text primary key,
  name text not null,
  birth_year integer,
  phone text,
  enroll_date date not null,
  leave_date date,
  class_id text references classes(id),
  status text not null, -- 'Mới nhập học', 'Đang học', 'Đã nghỉ'
  status_history jsonb default '[]'::jsonb,
  discount_rate numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create Fees Table (Tuition Payments)
create table fees (
  id text primary key,
  student_id text references students(id),
  amount integer not null,
  date date not null,
  method text, -- 'Tiền mặt', 'Chuyển khoản'
  note text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create Extra Attendance Table (Buổi học bổ sung)
create table extra_attendance (
  id text primary key,
  student_id text references students(id),
  date date not null,
  status boolean default true,
  fee integer,
  notes text,
  is_recurring boolean default false,
  recurring_pattern jsonb,
  created_by text,
  updated_by text,
  updated_at timestamp with time zone,
  change_history jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create Holidays Table (Lịch nghỉ)
create table if not exists holidays (
  id text primary key,
  date date not null,
  end_date date,
  description text,
  type text default 'Nghỉ Lễ', -- 'Nghỉ Lễ' or 'Nghỉ đột xuất'
  class_id text references classes(id),
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create Promotions Table
create table if not exists promotions (
  id bigint generated by default as identity primary key,
  class_id text references classes(id) on delete cascade,
  month text not null, -- Format: YYYY-MM
  discount_rate numeric default 0,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create Messages Table
create table if not exists messages (
  id bigint generated by default as identity primary key,
  author text default 'Admin',
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create Backups Table
create table if not exists backups (
  id bigint generated by default as identity primary key,
  data jsonb not null,
  filename text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table public.classes enable row level security;
alter table public.students enable row level security;
alter table public.fees enable row level security;
alter table public.extra_attendance enable row level security;
alter table public.holidays enable row level security;
alter table public.promotions enable row level security;
alter table public.messages enable row level security;
alter table public.backups enable row level security;

-- Helper function to get app secret from headers
create or replace function get_app_secret() returns text as $$
  select current_setting('request.headers', true)::json->>'x-app-secret';
$$ language sql stable set search_path = public;

-- Create Policies (Public Read, Restricted Write using app secret)
-- Classes
create policy "Public Read Access" on public.classes for select to anon using (true);
create policy "Restricted Write Access" on public.classes for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');

-- Students
create policy "Public Read Access" on public.students for select to anon using (true);
create policy "Restricted Write Access" on public.students for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');

-- Fees
create policy "Public Read Access" on public.fees for select to anon using (true);
create policy "Restricted Write Access" on public.fees for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');

-- Extra Attendance
create policy "Public Read Access" on public.extra_attendance for select to anon using (true);
create policy "Restricted Write Access" on public.extra_attendance for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');

-- Holidays
create policy "Public Read Access" on public.holidays for select to anon using (true);
create policy "Restricted Write Access" on public.holidays for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');

-- Promotions
create policy "Public Read Access" on public.promotions for select to anon using (true);
create policy "Restricted Write Access" on public.promotions for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');

-- Messages
create policy "Public Read Access" on public.messages for select to anon using (true);
create policy "Restricted Write Access" on public.messages for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');

-- Backups
create policy "Public Read Access" on public.backups for select to anon using (true);
create policy "Restricted Write Access" on public.backups for all to anon using (get_app_secret() = 'cqt263') with check (get_app_secret() = 'cqt263');
